version: '2'
services:
  service-miner:
    container_name: ${APP_NAME}-miner
    image: ${APP_IMAGE}
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=miner,elk
    labels:
      # Register container to filebeat via autodiscovery
      - co.elastic.metrics/hosts='elasticsearch:9200'
      - co.elastic.logs/json.keys_under_root=true
      - co.elastic.logs/json.add_error_key=true
      - co.elastic.logs/json.message_key=message
      - co.elastic.metrics/metricsets=status

  service-wallet:
    container_name: ${APP_NAME}-wallet
    image: ${APP_IMAGE}
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=elk
    depends_on:
      - service-miner
    labels:
      # Register container to filebeat via autodiscovery
      - co.elastic.metrics/hosts='elasticsearch:9200'
      - co.elastic.logs/json.keys_under_root=true
      - co.elastic.logs/json.add_error_key=true
      - co.elastic.logs/json.message_key=message
      - co.elastic.metrics/metricsets=status



