version: '2'
services:
  service-mainapp:
    extends:
      file: app.yml
      service: service-mainapp

  service-prometheus:
    container_name: ${APP_NAME}-prometheus
    image: prom/prometheus:v2.18.1
    volumes:
      - ./prometheus/:/etc/prometheus/
    command: '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - ${PROMETHEUS_PORT}:9090
    # On MacOS, remove next line and replace localhost by host.docker.internal in prometheus/prometheus.yml and
    # grafana/provisioning/datasources/datasource.yml
    #    network_mode: 'host' # to test locally running service
  service-grafana:
    container_name: ${APP_NAME}-grafana
    image: grafana/grafana:7.0.1
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - ${GRAFANA_PORT}:3000
